specVersion: 1.0.0
name: subql_behavioral_incentives
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: For Bifrost behavioral incentives project
repository: https://github.com/subquery/bifrost-subql-starter
schema:
  file: ./schema.graphql
network:
  # test ws://172.19.0.14:9866
  # proc: http://172.19.64.31:29933
  endpoint: ws://172.19.0.14:9866
  chainId: "0x4093592e79a9617b0f00d70c382a141b9e5110768e04db804f06c38deba0ef48"
  dictionary: https://api.subquery.network/sq/subquery/bifrost-parachain-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        #VtokenMinting module handlers
        - handler: handleVtokenMintingMinted
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Minted
        - handler: handleVtokenMintingRedeemed
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Redeemed
        #Tokens module handlers
        - handler: handleVtokenTransferOut
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Transfer
        - handler: handleCommissionPaid
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Transfer
        #Slp module handlers
        - handler: handleSlpHostingFeeCharged
          kind: substrate/EventHandler
          filter:
            module: slp
            method: HostingFeeCharged
